# common elements between dev and test
services:
  clients:
    ports:
      - 5173:5173
    build:
      context: ../..
      dockerfile: ./backup/backup-sdk/Dockerfile
    command: npm run dev
    volumes:
      - ./:/app/backup/backup-sdk/
      - ../../saflib/vue/:/app/saflib/vue/
      - ../../saflib/sdk/:/app/saflib/sdk/
