openapi: 3.0.0
info:
  title: tmp API
  version: 1.0.0
  description: API specification for the tmp service

paths:
  # Add your API routes here
  # Example:
  # /resource:
  #   get:
  #     $ref: "./routes/resource/list.yaml#/listResource"
  #   post:
  #     $ref: "./routes/resource/create.yaml#/createResource"
  # /resource/{id}:
  #   get:
  #     $ref: "./routes/resource/get.yaml#/getResource"
  #   put:
  #     $ref: "./routes/resource/update.yaml#/updateResource"
  #   delete:
  #     $ref: "./routes/resource/delete.yaml#/deleteResource"

components:
  schemas:
    Error:
      $ref: "./schemas/error.yaml"
    ProductEvent:
      $ref: "./events/index.yaml"
    # BEGIN WORKFLOW AREA schema-components FOR openapi/add-schema


    # END WORKFLOW AREA
