global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "caddy"
    static_configs:
      - targets: ["caddy:2020"]

  - job_name: "identity"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["identity:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

