openapi: 3.0.0
info:
  title: __service-name__ API
  version: 1.0.0
  description: API specification for the __service-name__ service

paths:
  # BEGIN WORKFLOW AREA route-paths FOR openapi/add-route
  __url-path__:
    __method__:
      $ref: "./routes/__group-name__/__target-name__.yaml#/__operationId__"
  # END WORKFLOW AREA

components:
  schemas:
    Error:
      $ref: "./schemas/error.yaml"
    ProductEvent:
      $ref: "./events/index.yaml"
    # BEGIN WORKFLOW AREA schema-components FOR openapi/add-schema
    __TargetName__:
      $ref: "./schemas/__target-name__.yaml"
    # END WORKFLOW AREA
