openapi: 3.0.0
info:
  title: Secrets API
  version: 1.0.0
  description: API specification for template-service service

paths:
  /secrets:
    get:
      $ref: "./routes/secrets-spec/list.yaml#/listSecrets"
    post:
      $ref: "./routes/secrets-spec/create.yaml#/createSecret"
  /secrets/{id}:
    put:
      $ref: "./routes/secrets-spec/update.yaml#/updateSecret"
    delete:
      $ref: "./routes/secrets-spec/delete.yaml#/deleteSecret"

components:
  schemas:
    # Add your shared schemas here
    Error:
      $ref: "./schemas/error.yaml"
    Secret:
      $ref: "./schemas/secret.yaml"
    SecretCreateRequest:
      $ref: "./schemas/secret-create-request.yaml"
    SecretUpdateRequest:
      $ref: "./schemas/secret-update-request.yaml"
