global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "caddy"
    static_configs:
      - targets: ["caddy:2020"]

  # BEGIN WORKFLOW AREA monolith FOR product/init
  - job_name: "__product-name__-monolith"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["__product-name__-monolith:3000"]
      
  # END WORKFLOW AREA

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
