name: Workflow Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  workflow-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # For grpc proto workflows
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install dependencies
        run: npm ci

      # Tests fail to run if this one package isn't installed
      - name: Install rollup for linux
        run: npm install @rollup/rollup-linux-x64-gnu

      # Main test. If this fails, one of the workflows is broken.
      - name: Run Workflow Integration Test
        run: npm exec saf-workflow run-scripts ./test-all-workflows.ts

      # just for debugging, checking all the files that got added/changed
      - name: Git status
        run: git status -uall
