name: Workflows with Git Commits

on:
  pull_request:
    branches:
      - main

jobs:
  workflow-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install dependencies
        run: npm ci

      - name: Install rollup for linux
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Undo package.json, package-lock.json
        run: git reset --hard

      - name: Git config name
        run: git config --global user.name "saflib CI"

      - name: Git config email
        run: git config --global user.email "noreply@saf-demo.online"

      - name: Run Workflow Integration Test
        run: ./test-git.sh
        working-directory: ./workflows-cli

      - name: Git status
        run: git status -uall
