name: Workflows in Run Mode

on:
  pull_request:
    branches:
      - main

jobs:
  workflow-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # For grpc proto workflows
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install dependencies
        run: npm ci

      # Main test. Runs the basic tests in agent mode, with a mock agent.
      - name: Run Workflow Integration Test
        run: npm exec saf-workflow kickoff ./test-all-steps.ts -- --skip-todos -r mock
        working-directory: ./workflows-cli

      # just for debugging, checking all the files that got added/changed
      - name: Git status
        run: git status -uall
